### ISSUE TITLE
Updating blogdown post about change of default argument ?

### ISSUE THREAD

**Issue by cderv** [knausb/knausb.github.io#2]
Hi,

From rstudio/blogdown#379, we discover that there was a change in `blogdown::new_post()` argument name some time ago that was of impact to new user and still documented. It is about `rmd = FALSE` that no more exist and was replace by `ext = getOption('blogdown.ext', '.md')` instead.

Maybe it is possible to update your post about that so that new user are not lost ?

* https://knausb.github.io/2017/06/a-first-post-using-blogdown/
* https://github.com/knausb/knausb.github.io/blob/sources/content/post/2017-06-03-a-first-post-using-blogdown.Rmd#L19

cheers

**Comment by knausb** [comment]
I've made the change. thanks for bringing this to my attention!

**Comment by fananan** [comment]
Thank you both!
